"""Metria core models for reproducible inference-systems studies."""

from .capabilities import (
    GeometryInspection,
    ModelGeometry,
    evaluate_turboquant_kv_capability,
    inspect_model_geometry,
)
from .comparison import compare_runs
from .execution import execute_run
from .hardware import capture_hardware_fingerprint
from .identity import (
    ArtifactManifest,
    Capability,
    CapabilitySet,
    HardwareFingerprint,
    ModelRef,
    RuntimeConfig,
    SupportLevel,
    WorkloadSpec,
)
from .inspection import (
    PreflightCapabilityResult,
    capability_inspection_to_mapping,
    inspect_run_capabilities,
)
from .models import (
    ComparisonPlan,
    CompatibilityIssue,
    CompatibilityReport,
    MetricDefinition,
    MetricDirection,
    MetricSample,
    MetricSummary,
    RunRecord,
    RunSpec,
    RunStatus,
    StudySpec,
    TreatmentSpec,
    TreatmentType,
)
from .protocols import MeasurementResult
from .recipes import (
    StudyRecipe,
    dump_study_recipe,
    load_study_recipe,
    run_spec_from_data,
    run_spec_to_data,
    study_recipe_digest,
    study_recipe_from_data,
    study_recipe_to_data,
    study_recipe_to_json,
)
from .records import (
    RUN_RECORD_SCHEMA,
    dump_run_record,
    load_run_record,
    run_evidence_digest,
    run_record_digest,
    run_record_from_data,
    run_record_to_data,
    run_record_to_json,
)
from .registry import (
    PluginAvailability,
    PluginDescriptor,
    PluginKind,
    RegistryBundle,
    builtin_registry,
    validate_study_availability,
)
from .runner import (
    STUDY_RESULT_SCHEMA,
    PersistedStudyResult,
    execute_recipe_to_directory,
)
from .study_execution import (
    PairwiseAnalysisStatus,
    StudyExecutionResult,
    StudyPairAnalysis,
    StudyPairComparison,
    execute_study,
)

__version__ = "0.1.0.dev0"

__all__ = [
    "RUN_RECORD_SCHEMA",
    "STUDY_RESULT_SCHEMA",
    "ArtifactManifest",
    "Capability",
    "CapabilitySet",
    "ComparisonPlan",
    "CompatibilityIssue",
    "CompatibilityReport",
    "GeometryInspection",
    "HardwareFingerprint",
    "MeasurementResult",
    "MetricDefinition",
    "MetricDirection",
    "MetricSample",
    "MetricSummary",
    "ModelGeometry",
    "ModelRef",
    "PairwiseAnalysisStatus",
    "PersistedStudyResult",
    "PluginAvailability",
    "PluginDescriptor",
    "PluginKind",
    "PreflightCapabilityResult",
    "RegistryBundle",
    "RunRecord",
    "RunSpec",
    "RunStatus",
    "RuntimeConfig",
    "StudyExecutionResult",
    "StudyPairAnalysis",
    "StudyPairComparison",
    "StudyRecipe",
    "StudySpec",
    "SupportLevel",
    "TreatmentSpec",
    "TreatmentType",
    "WorkloadSpec",
    "builtin_registry",
    "capability_inspection_to_mapping",
    "capture_hardware_fingerprint",
    "compare_runs",
    "dump_run_record",
    "dump_study_recipe",
    "evaluate_turboquant_kv_capability",
    "execute_recipe_to_directory",
    "execute_run",
    "execute_study",
    "inspect_model_geometry",
    "inspect_run_capabilities",
    "load_run_record",
    "load_study_recipe",
    "run_evidence_digest",
    "run_record_digest",
    "run_record_from_data",
    "run_record_to_data",
    "run_record_to_json",
    "run_spec_from_data",
    "run_spec_to_data",
    "study_recipe_digest",
    "study_recipe_from_data",
    "study_recipe_to_data",
    "study_recipe_to_json",
    "validate_study_availability",
]
